AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shopping-system

  Sample SAM Template for shopping-system
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FetchAllProducts:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: rest/
      Handler: app.FetchAllProducts
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        FetchAllProducts:
          Type: Api 
          Properties:
            Path: /FetchAllProducts
            Method: GET
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable

  CreateProducts:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: rest/
      Handler: app.CreateProducts
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateProducts:
          Type: Api 
          Properties:
            Path: /CreateProducts
            Method: POST
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable

  DeleteProduct:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: rest/
      Handler: app.DeleteProduct
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteProduct:
          Type: Api 
          Properties:
            Path: /DeleteProduct/{id}
            Method: DELETE
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable

  UpdateProduct:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: rest/
      Handler: app.UpdateProduct
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateProduct:
          Type: Api 
          Properties:
            Path: /UpdateProduct/{id}
            Method: PUT
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductsEndpoint:
    Description: "REST API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
